2025-07-01 11:48:05 | ERROR | Intento de divisi√≥n por cero: Traceback (most recent call last):
  File "/home/emptyman/Documentos/DatosPython/(6)Errores_Logging/Try-If.py", line 19, in <module>
    resultado = 10 / 0
                ~~~^~~
ZeroDivisionError: division by zero

